### PR TITLE
Add compilation_steps and header_only_templates articles

### PR DESCRIPTION
**Pull request by deqyra**
A couple articles about stuff that I find myself explaining a lot on TCCPP:

- what's really going on when you compile stuff
- why must templates reside in headers only

I tried to keep it short but I'm afraid it's a bit long. Any way I can test what it would look like and edit accordingly?

### CODE REVIEW

**Comment by deqyra** [comment]
I amended my commit and soft force-pushed it to fix inconsistent line breaks.

**Comment by deqyra** [comment]
I forgor to save before doing it so I did it again :skull: :brainlet:

**Comment by deqyra** [comment]
I reworded the contents of `compilation_steps.md` and renamed it to `undefined_reference.md`, since it better addresses this topic as a result of the rewording. It still acts as a refresher on the compilation steps and may be used as such. The word count went from 195 to 181. I feel like I can hardly do better, so ideas for further reduction are welcome if needed.

I also reworded the contents of `header_only_templates.md`, and split it so the bit about argument deduction is part of its own `template_argument_deduction.md` entry. The word count in the former went from 244 to 161 (code not included). The word count of the latter is 166 but it has quite some code excerpts along with it (although I inlined them as much as I could).

**Comment by deqyra** [comment]
After nearly 2 years I finally got around reworking everything in here.
This PR brings 3 new articles, whose content can be seen here (Discord message links):

[`compilation_steps.md`](https://discord.com/channels/331718482485837825/506274405500977153/1220341838280523888)

[`template_instantiation.md`](https://discord.com/channels/331718482485837825/506274405500977153/1220326543193014345)

[`template_argument_deduction.md`](https://discord.com/channels/331718482485837825/506274405500977153/1220334961530503258)

Since Wheatley doesn't seem to be rendering inline tags correctly, I went ahead and did this little bit of a montage to give a better idea of how the last two will (hopefully) look:
image
image

**Comment by eisenwave** [comment]
Thanks for the effort, but the article rendering is currently done by https://github.com/TCCPP/wheatley; you'll need to move the PR there.

**Comment by deqyra** [comment]
yeah Zelis ended up telling me as well. Thanks, I'll close this!

**Pull request closed without merging**
